a few documentation cleanups
nautobot/nautobot-plugin-chatops pull request #57
Opened 2021-06-16 21:28 UTC by tim-fiola

Added a line to do a nautobot server migration after editing the nautobot_config.py file as I've had to do that each time in order to get it to work

2021-06-16 21:35 UTC, smk4664 commented
Editing the Nautobot_config.py should not require running the migrate command.  I am interested if something else is happening when you run the migrate commad?  It should just take a restart of the Worker and the Server.

2021-06-17 02:55 UTC, jvanderaa requested changes
Thank you for the update!

2021-06-17 02:55 UTC, jvanderaa commented on docs/chat_setup/chat_setup.md
>  As a sudo-enabled user, restart the `nautobot` and `nautobot-worker` process after updating `nautobot_config.py`.
Combine into one if we believe the update is needed. I see this as more explicit than previously which is good, but we ask for the restart process twice.

2021-06-17 15:24 UTC, tim-fiola commented
Sorry folks. I should have opened this as a bug instead of a doc change.  Let me close this out and document what I see when I don't do the migration.

2021-06-17 15:24 UTC, closed without merging